DROP TABLE IF EXISTS rating CASCADE;
DROP TABLE IF EXISTS film_like CASCADE;
DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS friendship CASCADE;
DROP TABLE IF EXISTS film CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS status CASCADE;

---------------------------------------------------------
-- 1. Таблица пользователей
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    login VARCHAR(255) UNIQUE NOT NULL,
    birthday DATE NOT NULL
);

---------------------------------------------------------
-- 2. Статусы дружбы
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS status (
    status_id INT PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL
);

INSERT INTO status (status_id, status_name) VALUES
(1, 'PENDING'),
(2, 'CONFIRMED');

---------------------------------------------------------
-- 3. Дружба
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    status_id INT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (status_id) REFERENCES status(status_id)
);

---------------------------------------------------------
-- 4. Жанры
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS genre (
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(255) UNIQUE NOT NULL
);

INSERT INTO genre (genre_id, genre_name) VALUES
(1, 'Комедия'),
(2, 'Драма'),
(3, 'Мультфильм'),
(4, 'Триллер'),
(5, 'Документальный'),
(6, 'Боевик');


---------------------------------------------------------
-- 5. Рейтинги MPA
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS mpa (
    mpa_id INT PRIMARY KEY,
    mpa_name VARCHAR(20) NOT NULL
);

INSERT INTO mpa (mpa_id, mpa_name) VALUES
(1, 'G'),
(2, 'PG'),
(3, 'PG-13'),
(4, 'R'),
(5, 'NC-17');

---------------------------------------------------------
-- 6. Фильмы (без genre_id!)
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS film (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INT NOT NULL,
    mpa_id INT NOT NULL,
    FOREIGN KEY (mpa_id) REFERENCES mpa(mpa_id)
);

---------------------------------------------------------
-- 7. Связь фильм–жанр (многие-ко-многим)
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT NOT NULL,
    genre_id INT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES film(film_id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genre(genre_id)
);

---------------------------------------------------------
-- 8. Лайки
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS film_like (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES film(film_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
